#pragma once

#include <sdkconfig.h>


#define IGNORE_LEVEL_CONTROL_CLUSTER_START_UP_CURRENT_LEVEL


#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "ESP32P"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Lemke Development - ESP32C6 Pioneer"
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "5.5.5.5"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "5.5.5.5"

/*
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION 5
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 5
#define CHIP_DEVICE_CONFIG_DEVICE_CONFIGURATION_VERSION 5
#define CHIP_DEVICE_CONFIG_TEST_SERIAL_NUMBER "55555"
*/
